version: "3.4"

services:
  php:
    container_name: hotel-availability-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/hotel-availability-api
    # restart: unless-stopped
    volumes:
      - "./app:/var/www/hotel-availability-api"
      # - "./php-fpm/php.ini:/usr/local/etc/php/8.1/php.ini"
    ports:
      - "8003:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    deploy:
      labels:
        "app": "hotel-availability-api"
        "env": "development"
        "service": "php"
    links:
      - hotel-db

  hotel-db:
    container_name: hotel-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "hotel"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      # - "./mysql/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
    deploy:
      labels:
        "app": "hotel-availability-api"
        "env": "development"
        "service": "db"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    links:
      - hotel-db
